import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Header from "rbrgs-memories/components/Header/header";
import Body from "rbrgs-memories/components/Main/Body";
import Nav from "rbrgs-memories/components/Nav/Nav";

import { api } from "rbrgs-memories/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title> Roborregos Memories </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Nav>
        <main className=" flex min-h-screen flex-col items-center justify-center h-screen">
          <Body />
          
        </main>
      </Nav>

    </>
  );
}


